@extends('layouts.app')
@section('title','Edit Fuel Receive')
@section('content')
<div class="max-w-2xl">
  <h1 class="text-xl font-semibold mb-4">Edit Fuel Receive</h1>
  @if ($errors->any())<div class="rounded-md bg-red-50 border border-red-200 text-red-700 px-4 py-3 mb-4"><ul class="list-disc list-inside">@foreach ($errors->all() as $err) <li>{{ $err }}</li> @endforeach</ul></div>@endif
  <form method="POST" action="{{ route('fuel.receives.update', $receive) }}" class="space-y-4 bg-white p-6 rounded-lg border shadow-sm">
    @csrf @method('PUT')
    <div><label class="block text-sm font-medium text-slate-700">Site</label><select name="site_id" class="w-full border rounded px-3 py-2">@foreach ($sites as $s)<option value="{{ $s->id }}" @selected($receive->site_id === $s->id)>{{ $s->code }} — {{ $s->name }}</option>@endforeach</select></div>
    <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700">Receive At</label><input type="datetime-local" name="receive_at" value="{{ old('receive_at', $receive->receive_at->format('Y-m-d\TH:i')) }}" class="w-full border rounded px-3 py-2" required></div><div><label class="block text-sm font-medium text-slate-700">Volume (liter)</label><input type="number" step="0.01" name="volume" value="{{ old('volume',$receive->volume) }}" class="w-full border rounded px-3 py-2" required></div></div>
    <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700">Tank</label><select name="tank_id" class="w-full border rounded px-3 py-2"><option value="">— None —</option>@foreach ($tanks as $t)<option value="{{ $t->id }}" @selected($receive->tank_id === $t->id)>{{ $t->code }} — {{ $t->name }}</option>@endforeach</select></div><div><label class="block text-sm font-medium text-slate-700">Fuel Type</label><select name="fuel_type" class="w-full border rounded px-3 py-2"><option value="diesel" @selected($receive->fuel_type==='diesel')>Diesel</option><option value="gasoline" @selected($receive->fuel_type==='gasoline')>Gasoline</option></select></div></div>
    <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700">Supplier</label><input type="text" name="supplier" value="{{ old('supplier',$receive->supplier) }}" class="w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium text-slate-700">PO Number</label><input type="text" name="po_number" value="{{ old('po_number',$receive->po_number) }}" class="w-full border rounded px-3 py-2"></div></div>
    <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700">Invoice Number</label><input type="text" name="invoice_number" value="{{ old('invoice_number',$receive->invoice_number) }}" class="w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium text-slate-700">Price/Unit</label><input type="number" step="0.01" name="price_per_unit" value="{{ old('price_per_unit',$receive->price_per_unit) }}" class="w-full border rounded px-3 py-2"></div></div>
    <div class="grid grid-cols-2 gap-4"><div><label class="block text-sm font-medium text-slate-700">Vehicle Number</label><input type="text" name="vehicle_number" value="{{ old('vehicle_number',$receive->vehicle_number) }}" class="w-full border rounded px-3 py-2"></div><div><label class="block text-sm font-medium text-slate-700">Driver Name</label><input type="text" name="driver_name" value="{{ old('driver_name',$receive->driver_name) }}" class="w-full border rounded px-3 py-2"></div></div>
    <div><label class="block text-sm font-medium text-slate-700">Reference No</label><input type="text" name="reference_no" value="{{ old('reference_no',$receive->reference_no) }}" class="w-full border rounded px-3 py-2"></div>
    <div><label class="block text-sm font-medium text-slate-700">Notes</label><textarea name="notes" rows="2" class="w-full border rounded px-3 py-2">{{ old('notes',$receive->notes) }}</textarea></div>
    <div class="flex gap-3"><button class="px-4 py-2 rounded bg-indigo-600 text-white">Update</button><a href="{{ route('fuel.receives.index', ['site' => $siteId]) }}" class="px-4 py-2 rounded border border-slate-300">Batal</a></div>
  </form>
</div>
@endsection
